package com.nsyw.routerdemo.router_compiler;

/**
 * @author : yetianhua
 * @project: RouterDemo
 * @date : 2019-12-06
 * @time : 16:05
 * @note :
 */
public class consts {
    public static final String SEPARATOR = "$$";
    public static final String PROJECT = "Router";
    public static final String WARNING_TIPS = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY AROUTER.";
    public static final String METHOD_LOAD_INTO = "loadInto";
    public static final String IROUTE_PACKAGE = "com.nsyw.routerdemo.router_compiler";
    public static final String PACKAGE_OF_GENERATE_FILE = "com.nsyw.routerdemo.routes";
    public static final String PACKAGE = "com.nsyw.routerdemo";
    public static final String TEMPLATE_PACKAGE = ".template";
    public static final String IROUTE = IROUTE_PACKAGE + ".IRoute";
    public static final String NAME_OF_ROUTE = PROJECT + SEPARATOR + "App"+SEPARATOR;
    public static final String KEY_MODULE_NAME = "ROUTER_MODULE_NAME";
    public static final String ACTIVITY = "android.app.Activity";
}
